events { worker_connections 1024; }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    gzip          on;
    gzip_types    text/plain text/css application/javascript application/json image/svg+xml;

    upstream node_api   { server 127.0.0.1:4000; keepalive 32; }
    upstream python_api { server 127.0.0.1:4001; keepalive 16; }

    server {
        listen 3000;
        server_name _;

        location / {
            root  /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            proxy_pass         http://node_api;
            proxy_http_version 1.1;
            proxy_set_header   Host $host;
            proxy_read_timeout 60s;
        }

        location /ws {
            proxy_pass          http://node_api;
            proxy_http_version  1.1;
            proxy_set_header    Upgrade    $http_upgrade;
            proxy_set_header    Connection "upgrade";
            proxy_set_header    Host       $host;
            proxy_read_timeout  3600s;
        }

        location /papi/ {
            proxy_pass         http://python_api/;
            proxy_http_version 1.1;
            proxy_set_header   Host $host;
            proxy_read_timeout 30s;
        }
    }
}
