export const COUNTRY_NAME: Record<string, string> = {
  DE: 'Deutschland',
  US: 'USA',
  FR: 'Frankreich',
  GB: 'UK',
  NL: 'Niederlande',
  CN: 'China',
  RU: 'Russland',
  BR: 'Brasilien',
  IN: 'Indien',
  SG: 'Singapur',
  PL: 'Polen',
  IT: 'Italien',
  ES: 'Spanien',
  SE: 'Schweden',
  CH: 'Schweiz',
  AT: 'Österreich',
  UA: 'Ukraine',
  TR: 'Türkei',
  JP: 'Japan',
  KR: 'Korea',
  AU: 'Australien',
  CA: 'Kanada',
}
